apiVersion: v1
kind: ConfigMap
metadata:
  name: adminapi-cm
data:
  # property-like keys; each key maps to a simple value
  kafkabrokers: "localhost:9093"
  maxrecords: "5"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adminclient-props
data:
  server.properties: |
    kafkabrokers=localhost:9092
    num.stream.threads=10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapi
  labels:
    app: adminapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: adminapi
  template:
    metadata:
      labels:
        app: adminapi
    spec:
      containers:
        - name: adminapi
          image: adminapi
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: adminapi-cm
                  key: kafkabrokers
          envFrom:
            - configMapRef:
                name: adminapi-cm
          volumeMounts:
            - name: server-properties-from-cm
              mountPath: /etc/config
      volumes:
        - name: server-properties-from-cm
          configMap:
            name: adminclient-props
